### ISSUE TITLE
.github/workflows/*.yaml files are not checked

### ISSUE THREAD

**Issue by Tenzer** [woodruffw/zizmor-pre-commit#5]
While setting up the Zizmor pre-commit hook on a bunch of repositories, I noticed on one repository it said there weren't any files to check, despite the `.github/workflows/` folder having YAML files inside of it.

I then noticed the files inside the folder were named with a `.yaml` extension and not `.yml` like I had in the other repositories I had set up, so it appears like the pre-commit hook doesn't pick up `.github/workflows/*.yaml` files.

I've made a small repository to reproduce this issue: https://github.com/Tenzer/zizmor-pre-commit-test.

If you clone the repository and run `pre-commit run --all-files` I would expect it to complain about both `test.yml` and `test.yaml` since they both are configured to clone the repository and don't have `persist-credentials` configured. I am however only seeing it complain about `test.yml`:
```sh
~/git/zizmor-pre-commit-test % pre-commit run --all-files
zizmor...................................................................Failed
- hook id: zizmor
- exit code: 13

🌈 completed test.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> /Users/jeppe/my-git/zizmor-pre-commit-test/.github/workflows/test.yml:11:9
   |
11 |         - name: Checkout
   |  _________-
12 | |         uses: actions/checkout@v4
   | |__________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

2 findings (1 suppressed): 0 unknown, 0 informational, 0 low, 1 medium, 0 high
```

Running Zizmor (0.8.0) directly does capture both files:
```sh
~/git/zizmor-pre-commit-test % zizmor .
🌈 completed test.yaml
🌈 completed test.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> /Users/jeppe/my-git/zizmor-pre-commit-test/.github/workflows/test.yaml:11:9
   |
11 |         - name: Checkout
   |  _________-
12 | |         uses: actions/checkout@v4
   | |__________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> /Users/jeppe/my-git/zizmor-pre-commit-test/.github/workflows/test.yml:11:9
   |
11 |         - name: Checkout
   |  _________-
12 | |         uses: actions/checkout@v4
   | |__________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

4 findings (2 suppressed): 0 unknown, 0 informational, 0 low, 2 medium, 0 high
```
so I assume this is a problem specific to the pre-commit hook.

I am using pre-commit 4.0.1 which is the latest version as of writing.

**Comment by Tenzer** [comment]
Ah, I had a look in the `.pre-commit-hooks.yaml` file and saw that it was using `types: [yaml]` which ought to work, but I hadn't checked if that had changed since the latest tag.

Perhaps it makes sense to allow for an extra version number in the tagging format, so you have `<zizmor version>-<pre-commit hook version>`? That way, you could release a version `0.8.0-1` with this fix, without relying on a new zizmor release to be available first.

**Comment by graingert** [comment]
Yeah you'll need to make a point release of the regular zizmor, then we can see if the automatic deployment works for zizmor-pre-commit, if it doesn't we can poke it manually

**Comment by graingert** [comment]
We could release zizmor-pre-commit 0.8.0.1 if we want to separate releases of zizmor and zpc

**Comment by woodruffw** [comment]
Ah yeah, keeping these in sync makes sense. I'm due for a 0.9.0 release anyways so I'll kick that off.

**Comment by woodruffw** [comment]
0.9.0 is cut and should be published shortly.

**Comment by woodruffw** [comment]
Looks like the auto-sync failed:

```
Run git push origin HEAD:refs/heads/main
fatal: could not read Username for 'https://github.com/': No such device or address
Error: Process completed with exit code 128.
```

**Comment by woodruffw** [comment]
> Otherwise the workflow doesn't have any credentials for updating the repository.

Hoisted on my own petard 🙂 -- thanks for pointing that out, I'll update it.

**Comment by woodruffw** [comment]
Fixed with #6, although I suspect this might still fail since the default `GITHUB_TOKEN` might not have enough permissions to `git push` or do a release. But we'll see 🙂

**Comment by Tenzer** [comment]
Yes, I believe you probably need to add:
```yaml
permissions:
  contents: write
```

**Comment by woodruffw** [comment]
That did the trick! This repo should now be on the latest, which both includes the fix and the newest version of `zizmor`.

Thanks for reporting and helping out here @Tenzer!

**Comment by Tenzer** [comment]
Thanks!
